### ISSUE TITLE
update vector: fail with status 500

### ISSUE THREAD

**Issue by unsady** [weaviate/typescript-client#92]
Server respond with error when I try to upload this image https://images-na.ssl-images-amazon.com/images/I/51Uc-WH2PTL.jpg

``` typescript
await client.data
        .creator()
        .withClassName('Test')
        .withProperties({ asin, image })
        .do()
```

`Error: usage error (500): {"error":[{"message":"update vector: fail with status 500"}]}`

**Comment by tsmith023** [comment]
Hi @unsady, this seems to be an issue with the vectorizer that you're using and its ability to vectorize an image.

Since this repository hosts the Weaviate TypeScript-client, it's primarily a place to post bug reports and make feature requests of the client itself. I recommend you posting your question on the [Weaviate community forum](https://forum.weaviate.io) where your issue will gain more traction and be answered faster!
